---
- name: Copy authorized keys
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa.pub
    dest: /etc/dropbear/authorized_keys
    mode: u=rw,g=,o=

- name: Restrict SSH
  uci:
    command: section
    config: dropbear
    name: '@dropbear[0]'
    type: dropbear
    value:
      Interface: lan
      PasswordAuth: 'off'
      RootPasswordAuth: 'off'

- name: Commit
  uci:
    command: commit
    key: dropbear

- name: Reload config
  ansible.builtin.command: reload_config
  changed_when: false
