- name: OpenWRT custom setup playbook
  hosts: openwrt
  remote_user: root
  vars_files:
    - overrided_vars.yml

  roles:
    - gekmihesg.openwrt
    - build_firmware
    - install_firmware
    - resize_disk
    - secure_ssh
    - setup_system
    - setup_network
    - install_sqm
    - install_ddns
    - install_docker
    - install_docker_unifi
    - install_adguardhome
    - post_install
