- name: OpenWRT custom setup playbook
  hosts: openwrt
  remote_user: root
  vars:
    install_firmware: true
    install_resize: true
    install_essentials: true
    install_ssh: true
    install_system: true
    install_network: true
    install_sqm: true
    install_ddns: true
    install_stubby: true
    install_firewall: true
    install_docker: true
  vars_files:
    - overrided_vars.yml

  roles:
    - gekmihesg.openwrt

  tasks:
    - name: Include install firmware tasks
      ansible.builtin.include_tasks: tasks/firmware.yml
      when: install_firmware

    - name: Include install enable WAN tasks
      ansible.builtin.include_tasks: tasks/enable_wan.yml
      when: install_firmware

    - name: Include install resize tasks
      ansible.builtin.include_tasks: tasks/resize.yml
      when: install_resize

    - name: Include install essentials tasks
      ansible.builtin.include_tasks: tasks/essentials.yml
      when: install_essentials

    - name: Include install ssh tasks
      ansible.builtin.include_tasks: tasks/ssh.yml
      when: install_ssh

    - name: Include install system tasks
      ansible.builtin.include_tasks: tasks/system.yml
      when: install_system

    - name: Include install network tasks
      ansible.builtin.include_tasks: tasks/network.yml
      when: install_network

    - name: Include install sqm tasks
      ansible.builtin.include_tasks: tasks/sqm.yml
      when: install_sqm

    - name: Include install ddns tasks
      ansible.builtin.include_tasks: tasks/ddns.yml
      when: install_ddns

    - name: Include install stubby tasks
      ansible.builtin.include_tasks: tasks/stubby.yml
      when: install_stubby

    - name: Include install firewall tasks
      ansible.builtin.include_tasks: tasks/firewall.yml
      when: install_firewall

    - name: Include install docker tasks
      ansible.builtin.include_tasks: tasks/docker.yml
      when: install_docker



  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks:
        file: handlers/main.yml
