- name: OpenWRT custom setup playbook
  hosts: openwrt
  remote_user: root
  vars_files:
    - overrided_vars.yml
  vars:
    network_brlan_ports:
      - eth0

  roles:
    - gekmihesg.openwrt
    - build_firmware
    - install_firmware
    - resize_disk
    - secure_ssh
    - setup_system
    - setup_network
    - install_sqm
    - install_ddns
    - install_docker
    - install_docker_unifi
    - install_adguardhome

  tasks:
    # opkg install python3-requests losetup parted fdisk resize2fs
    - name: Remove unused packages
      community.general.opkg:
        name: "{{ item }}"
        state: absent
        autoremove: true
      loop:
        - python3-requests
        - losetup
        - parted
        - fdisk
        - resize2fs
      when: false
