- name: OpenWRT custom setup playbook
  hosts: openwrt
  remote_user: root
  vars_files:
    - overrided_vars.yml
  vars:
    firmware_version: 22.03.4
    firmware_target: x86
    firmware_subtarget: 64
    firmware_profile: generic
    firmware_image: ext4-combined-efi
    firmware_output: /tmp/firmware.img.gz
    network_brlan_ports:
      - eth0

  roles:
    - gekmihesg.openwrt
    - build_firmware
    # - download_firmware
    - install_firmware
    - enable_wan
    - resize_disk
    - essential_packages
    - secure_ssh
    - setup_system
    - setup_network
    - install_sqm
    - install_ddns
    - install_docker
    - install_docker_unifi
    - install_adguardhome

  tasks:
    - name: Remove python
      community.general.opkg:
        name: "{{ packages | join(',') }}"
        state: absent
        autoremove: true
      vars:
        packages:
          - python3-requests
          - losetup
          - resize2fs
          - parted
          - fdisk
