- name: OpenWRT custom setup playbook
  hosts: openwrt
  remote_user: root
  vars_files:
    - overrided_vars.yml
  vars:
    network_brlan_ports:
      - eth0
    install_firmware_uri: >-
      /tmp/openwrt-imagebuilder-22.03.4-x86-64.Linux-x86_64/bin/targets/x86/64/openwrt-22.03.4-x86-64-generic-ext4-combined-efi.img.gz

  roles:
    - gekmihesg.openwrt
#    - build_image
    - install_firmware
    - enable_wan
    - resize_disk
    - essential_packages
    - secure_ssh
    - setup_system
    - setup_network
    - install_sqm
    - install_ddns
    - install_docker
    - install_docker_unifi
    - install_adguardhome

  tasks:
    - name: Remove python
      community.general.opkg:
        name: python3-requests
        state: absent
        autoremove: true
