- name: OpenWRT custom setup playbook
  hosts: openwrt
  remote_user: root
  vars_files:
    - secret_vars.yml
  vars:
    network_brlan_ports:
      - eth0
      - eth2
      - eth3
      - eth4
      - eth5

  roles:
    - gekmihesg.openwrt
    - secure_ssh
    - setup_system
    - setup_network
    - install_sqm
    - install_adguardhome
    - install_ddns
    - install_docker
    - install_docker_unifi

  tasks:
    - name: Remove python
      community.general.opkg:
        name: python3-requests
        state: absent
        autoremove: true
    - name: Reboot
      ansible.builtin.include_role:
        name: reboot

