---
# tasks file for enable_wan# Minimal configuration to have internet after upgrade with my ISP
- name: Set wan vendorid option
  uci:
    command: section
    config: network
    type: interface
    name: wan
    value:
      vendorid: "{{ wan_vendorid }}"

- name: Commit network
  uci:
    command: commit
    key: network

- name: Reload config
  ansible.builtin.command: reload_config
  changed_when: false

- name: Wait for internet access
  ansible.builtin.command:
    cmd: wget --timeout=5 --spider https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.gz
  changed_when: false
  register: _wget_packages_result
  retries: 12
  until: _wget_packages_result.rc == 0

# Needed to update opkg and ensure mandatory packages for
# ekmihesg.openwrt role to work are installed
- name: Install firmware, re-install gekmihesg.openwrt role
  ansible.builtin.include_role:
    name: gekmihesg.openwrt
  vars:
    openwrt_install_recommended_packages: true
