---
# tasks file for enable_wan# Minimal configuration to have internet after upgrade with my ISP
- name: Set wan vendorid option
  uci:
    command: section
    config: network
    type: interface
    name: wan
    value:
      vendorid: neufbox_NB6VAC-directAccess

- name: Commit network
  uci:
    command: commit
    key: network

- name: Reload config
  ansible.builtin.command: reload_config
  changed_when: false

- name: Wait for internet access
  ansible.builtin.get_url:
    url: https://downloads.openwrt.org/releases/22.03.4/packages/x86_64/packages/Packages.asc
    dest: /tmp/Packages.asc
    mode: u=rw,g=r,o=r
    timeout: 5
  changed_when: false
  register: _geturl_packages_result
  retries: 12
  delay: 0
  until: _geturl_packages_result.msg.find("OK") == 0
  delegate_to: localhost
  become: false

# Needed to update opkg and ensure mandatory packages for
# ekmihesg.openwrt role to work are installed
- name: Install firmware, re-install gekmihesg.openwrt role
  ansible.builtin.include_role:
    name: gekmihesg.openwrt
  vars:
    openwrt_install_recommended_packages: true
