---
# https://openwrt.org/docs/guide-user/installation/installation_methods/sd_card#expanding_the_filesystem
# https://openwrt.org/docs/guide-user/installation/openwrt_x86#resizing_partitions
# https://forum.openwrt.org/t/howto-resizing-root-partition-on-x86-march-2023-edition

- name: Identify root disk and partition
  ansible.builtin.include_tasks: identify_root_disk.yml

- name: Install needed packages
  community.general.opkg:
    name: "{{ item }}"
    state: present
  loop:
    - losetup
    - resize2fs
    - parted
    - fdisk
  when: is_free_space

- name: Fix partition table
  ansible.builtin.shell: |
   set -o pipefail
   printf "w" | fdisk {{ root_disk.path }}
  register: fix_partition_table_result
  changed_when: fix_partition_table_result.rc == 0
  when: is_free_space

- name: Resize root partition
  ansible.builtin.command: parted -s {{ root_disk.path }} resizepart {{ root_partition.partn }} 100%
  register: resize_partition_result
  changed_when: resize_partition_result.rc == 0
  when: is_free_space

- name: Reboot
  ansible.builtin.include_role:
    name: reboot
  when: is_free_space

- name: Identify root disk and partition
  ansible.builtin.include_tasks: identify_root_disk.yml
  when: is_free_space

# /dev/loop0
- name: Get loop partition
  ansible.builtin.command: losetup -f
  register: get_loop_ext4_result
  changed_when: false
  when: is_free_space

# loop = /dev/loop0
- name: Set loop partition
  ansible.builtin.set_fact:
    loop_partition: >-
      "{{ get_loop_ext4_result.stdout }}"
  when: is_free_space

- name: Invert loop root
  ansible.builtin.command: losetup {{ loop_partition }} {{ root_partition.path }}
  register: invert_loop_result
  changed_when: invert_loop_result.rc == 0
  when: is_free_space

- name: Resize root filesystem
  ansible.builtin.command: resize2fs -f {{ loop_partition }}
  register: rootfs_result
  changed_when: rootfs_result.rc == 0
  when: is_free_space

- name: Reboot
  ansible.builtin.include_role:
    name: reboot
  when: is_free_space and rootfs_result.changed

- name: Identify root disk and partition
  ansible.builtin.include_tasks: identify_root_disk.yml
  when: is_free_space

- name: Remove unused packages
  community.general.opkg:
    name: "{{ item }}"
    state: absent
    force: removal-of-dependent-packages
  loop:
    - losetup
    - parted

- name: Remove resize2fs package without autoremove
  community.general.opkg:
    name: resize2fs
    state: absent
