---
- name: Trigger reboot
  nohup:
    command: reboot

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 60

- name: Wait for internet access
  ansible.builtin.command:
    cmd: wget --timeout=5 --spider https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.gz
  changed_when: false
  register: _wget_packages_result
  retries: 12
  until: _wget_packages_result.rc == 0

- name: Update opkg cache
  community.general.opkg:
    name: opkg
    update_cache: true
  register: _opkg_update
  failed_when: _opkg_update.failed
  changed_when: not _opkg_update.failed
