#!/bin/sh
set -x

# https://openwrt.org/docs/guide-user/advanced/expand_root?s[]=resize#instructions_manual
# OpenWrt 24.10+ - Resize root partition to 100% of disk

# Redirect debug output to log file
{
    [ -e /etc/rootpt-resize-ok ] && exit 0

    lock -n /var/lock/root-resize

    ROOT_BLK="$(readlink -f /sys/dev/block/"$(awk -e '$9=="/dev/root"{print $3}' /proc/self/mountinfo)")"
    ROOT_DISK="/dev/$(basename "${ROOT_BLK%/*}")"
    ROOT_PART="/dev/${ROOT_BLK##*/}"
    ROOT_PART_NB="${ROOT_BLK##*[^0-9]}"

    # Resize partition to 100% of disk
    parted -f -s "${ROOT_DISK}" resizepart "${ROOT_PART_NB}" 100%

    # Update GRUB config with new PARTUUID
    ROOT_UUID="$(blkid -s PARTUUID -o value "${ROOT_PART}")"
    sed -i "s|PARTUUID=[0-9a-f-]*|PARTUUID=${ROOT_UUID}|g" /boot/grub/grub.cfg

    touch /etc/rootpt-resize-ok
} > /var/log/rootpt-resize 2>&1

reboot
