---
# Minimal configuration to have internet after upgrade
- name: Enable WAN, uci set wan vendorid option
  uci:
    command: set
    key: network.wan
    value:
      vendorid: neufbox_NB6VAC-directAccess

- name: Enable WAN, uci commit network
  uci:
    command: commit
    key: network

- name: Enable WAN, restart network service
  ansible.builtin.service:
    name: network
    state: restarted
  notify: Wait for internet access

- name: Enable WAN, wait for internet access
  ansible.builtin.meta: flush_handlers

# Needed to update opkg and ensure mandatory packages for
# ekmihesg.openwrt role to work are installed
- name: Enable WAN, re-install gekmihesg.openwrt role
  ansible.builtin.include_role:
    name: gekmihesg.openwrt
  vars:
    openwrt_install_recommended_packages: true
