---
- name: Setup essentials, install packages
  community.general.opkg:
    name: "{{ packages | join(',') }}"
    state: present
  vars:
    packages:
      - luci
      - htop
      - vim
      - less
      - dmesg
      - usbutils
      - pciutils
      - lm-sensors
      - smartmontools
