---
- name: Setup docker, install packages
  community.general.opkg:
    name: "{{ packages | join(',') }}"
    state: present
  vars:
    packages:
      - htop
      - vim
      - less
      - usbutils
      - dmesg
      - ip-full
      - ifstat
      - luci
      - pciutils
      - lm-sensors
      - smartmontools
