---
- name: Install firmware, download firmware
  ansible.builtin.get_url:
    url: "{{ firmware_url }}"
    dest: "/tmp/{{ firmware_url | basename }}"
    checksum: "{{ firmware_checksum }}"
    mode: u=rw,g=r,o=r
  delegate_to: 127.0.0.1
  become: false

- name: Install firmware, copy image to router
  ansible.builtin.copy:
    src: "/tmp/{{ firmware_url | basename }}"
    dest: /tmp/openwrt.img.gz
    mode: u=rw,g=r,o=r

- name: Install firmware, start sysupgrade process
  nohup:
    command: sysupgrade -n /tmp/openwrt.img.gz
  notify: Wait for connection

- name: Install firmware, wait for reboot
  ansible.builtin.meta: flush_handlers
