---
- name: Trigger reboot
  nohup:
    command: reboot

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 300
    delay: 10

- name: Wait for internet access
  ansible.builtin.wait_for:
    host: downloads.openwrt.org
    port: 443
    delay: 5
  delegate_to: 127.0.0.1

- name: Update opkg cache
  community.general.opkg:
    name: opkg
    update_cache: true
  register: _update
  failed_when: _update.failed
  changed_when: not _update.failed
