---
# https://openwrt.org/docs/guide-user/installation/openwrt_x86#resizing_partitions

- name: Resize root partition, initial list of packages to install
  ansible.builtin.set_fact:
    resize_packages:
      - lsblk
      - losetup
      - resize2fs
      - parted

- name: Resize root partition, install needed packages
  community.general.opkg:
    name: "{{ resize_packages | join(',') }}"
    state: present

- name: Resize root partition, get boot device
  ansible.builtin.command: sed -n -e "\|\s/boot\s.*$|{s///p;q}" /etc/mtab
  register: _get_boot_result
  changed_when: false

- name: Resize root partition, set fact resize_boot
  ansible.builtin.set_fact:
    resize_boot: "{{ _get_boot_result.stdout }}"

- name: Resize root partition, set fact resize_part and resize_disk
  ansible.builtin.set_fact:
    resize_part: "{{ resize_boot[-1] }}"
    resize_disk: "{{ resize_boot[:-1] }}"

- name: Resize root partition, set fact resize_root
  ansible.builtin.set_fact:
    resize_root: "{{ resize_disk }}{{ (resize_part | int + 1) | string }}"

- name: Resize root partition, get root partition uuid
  ansible.builtin.command: "lsblk -n -o PARTUUID {{ resize_root }}"
  register: _get_rootuuid_result
  changed_when: false

- name: Resize root partition, set fact resize_uuid
  ansible.builtin.set_fact:
    resize_uuid: "{{ _get_rootuuid_result.stdout }}"

- name: Resize root partition, get loop partition
  ansible.builtin.command: losetup -f
  register: _get_loop_result
  changed_when: false

- name: Resize root partition, set fact resize_loop
  ansible.builtin.set_fact:
    resize_loop: "{{ _get_loop_result.stdout }}"

- name: Resize root partition, resize action
  ansible.builtin.shell: |
    set -o pipefail
    echo fix | parted -l ---pretend-input-tty
    parted -s {{ resize_disk }} resizepart {{ resize_root[-1] }} 100%
    sed -i -r -e "s|(PARTUUID=)\S+|\1{{ resize_uuid }}|g" /boot/grub/grub.cfg
    losetup {{ resize_loop }} {{ resize_root }}
    resize2fs -f {{ resize_loop }}
  register: _resize_script_result
  changed_when: _resize_script_result.rc == 0
  notify:
    - Reboot
    - Wait for connection

- name: Reboot now
  ansible.builtin.meta: flush_handlers
