---
- name: Setup stubby, remove dnsmasq package
  community.general.opkg:
    name: dnsmasq
    state: absent

- name: Setup stubby, install stubby & dnsmasq-full packages
  community.general.:
    name: "{{ packages | join(',') }}"
    state: present
  vars:
    packages:
      - dnsmasq-full
      - stubby

- name: Setup stubby, global configuration
  notify: Apply
  uci:
    command: section
    config: stubby
    name: global
    type: stubby
    value:
      manual: 0
      trigger: wan
      dns_transport: GETDNS_TRANSPORT_TLS
      tls_authentication: 1
      tls_query_padding_blocksize: 128
      appdata_dir: /var/lib/stubby
      edns_client_subnet_private: 1
      idle_timeout: 10000
      round_robin_upstreams: 1
      listen_address:
        - '127.0.0.1@5453'
        - '0::1@5453'
      tls_ciphersuites: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256'
      tls_min_version: '1.3'
      dnssec_return_status: 1
      triggerdelay: 10
    replace: true

- name: "Setup stubby, add resolver {{ item.0.tls_auth_name + ' : ' + item.1 }}"
  notify: Apply
  uci:
    command: section
    config: stubby
    name: "@resolver[{{ index }}]"
    type: resolver
    value:
      tls_auth_name: "{{ item.0.tls_auth_name }}"
      address: "{{ item.1 }}"
  loop: "{{ resolvers | subelements('address') }}"
  loop_control:
    index_var: index
  vars:
    resolvers:
      - tls_auth_name: cloudflare-dns.com
        address:
          - '2606:4700:4700::1111'
          - '2606:4700:4700::1001'
          - '1.1.1.1'
          - '1.0.0.1'
      - tls_auth_name: dns.opendns.com
        address:
          - '2620:119:35::35'
          - '620:119:53::53'
          - '208.67.222.222'
          - '208.67.220.220'
