---
# https://openwrt.org/docs/guide-user/services/dns/dot_dnsmasq_stubby
# https://github.com/openwrt/packages/blob/master/net/stubby/files/README.md

- name: Setup stubby, install stubby
  community.general.opkg:
    name: stubby
    state: present

- name: Setup stubby, replace dnsmask by dnsmask-full
  community.general.opkg:
    name: dnsmasq-full
    state: present
  register: _stubby_check_dnsmasq_full_result
  failed_when: false
  changed_when: false

- name: Setup stubby, replace dnsmask by dnsmask-full
  ansible.builtin.shell: >
    opkg install dnsmasq-full --download-only &&
    opkg remove dnsmasq &&
    opkg install dnsmasq-full --cache . && rm *.ipk
  register: _stubby_install_dnsmasq_full_result
  changed_when: _stubby_install_dnsmasq_full_result.rc == 0
  when: |
    _stubby_check_dnsmasq_full_result.msg is defined and
    _stubby_check_dnsmasq_full_result.msg.find('Cannot install package dnsmasq-full') != -1

- name: Setup stubby, remove dnsmask-full original saved config created by yhe installation
  ansible.builtin.file:
    path: /etc/config/dhcp-opkg
    state: absent

- name: Setup stubby, global configuration
  notify: Apply
  uci:
    command: section
    config: stubby
    name: global
    type: stubby
    value:
      manual: 0
      trigger: wan
      dns_transport: GETDNS_TRANSPORT_TLS
      tls_authentication: 1
      tls_query_padding_blocksize: 128
      appdata_dir: /var/lib/stubby
      edns_client_subnet_private: 1
      idle_timeout: 10000
      round_robin_upstreams: 1
      listen_address:
        - '127.0.0.1@5453'
        - '0::1@5453'
      tls_ciphersuites: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256'
      tls_min_version: '1.3'
      dnssec_return_status: 1
      triggerdelay: 0
    replace: true

- name: "Setup stubby, add resolver {{ item.0.tls_auth_name + ' : ' + item.1 }}"
  notify: Apply
  uci:
    command: section
    config: stubby
    name: "@resolver[{{ index }}]"
    type: resolver
    value:
      tls_auth_name: "{{ item.0.tls_auth_name }}"
      address: "{{ item.1 }}"
  loop: "{{ resolvers | subelements('address') }}"
  loop_control:
    index_var: index
  vars:
    resolvers:
      - tls_auth_name: cloudflare-dns.com
        address:
          - '2606:4700:4700::1111'
          - '2606:4700:4700::1001'
          - '1.1.1.1'
          - '1.0.0.1'
      - tls_auth_name: dns.opendns.com
        address:
          - '2620:119:35::35'
          - '620:119:53::53'
          - '208.67.222.222'
          - '208.67.220.220'

- name: Setup stubby, configure dnsmasq
  notify: Apply
  uci:
    command: set
    key: dhcp.@dnsmasq[0]
    value:
      noresolv: 1
      proxydnssec: 1
      server:
        - '127.0.0.1#5453'
        - '0::1#5453'
