---
- name: Install docker packages
  community.general.opkg:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - dockerd
    - luci-app-dockerman
    - docker-compose
    - kmod-macvlan

- name: Disable iptable support
  uci:
    command: section
    config: dockerd
    name: globals
    type: globals
    value:
      iptables: 0

- name: Disable Docker firewall default rules
  uci:
    command: absent
    config: dockerd
    section: firewall
