#!/bin/sh

# https://github.com/openwrt/packages/blob/master/net/stubby/files/README.md
# https://openwrt.org/docs/guide-user/services/dns/dot_dnsmasq_stubby
# https://forum.openwrt.org/t/tutorial-no-cli-configuring-dns-over-tls-with-luci-using-stubby-and-dnsmasq/29143/
# https://openwrt.org/docs/guide-user/firewall/fw3_configurations/intercept_dns

[ "$(uci get network.wan.peerdns)" = "0" ] && exit 0

# Never sending DNS requests to ISP provided DNS servers
uci set network.wan.peerdns="0"
uci set network.wan.dns="127.0.0.1"
uci set network.wan6.peerdns="0"
uci set network.wan6.dns="0::1"
uci commit network

# Enable DNS encryption
uci set dhcp.@dnsmasq[0].noresolv="1"
uci set dhcp.@dnsmasq[0].localuse="1"
uci set dhcp.@dnsmasq[0].proxydnssec="1"
uci set dhcp.@dnsmasq[0].filterwin2k="1"
uci delete dhcp.@dnsmasq[0].server
uci get stubby.global.listen_address \
| sed -e "s/\s/\n/g;s/@/#/g" \
| while read -r STUBBY_SERV
do uci add_list dhcp.@dnsmasq[0].server="${STUBBY_SERV}"
done
uci commit dhcp

stubby_add_resolver() {
    uci add stubby resolver
    uci set stubby.@resolver[-1].tls_auth_name="$1"
    uci set stubby.@resolver[-1].address="$2"
}

uci set stubby.global.tls_ciphersuites="TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256"
uci set stubby.global.tls_min_version="1.3"
uci set stubby.global.dnssec_return_status="1"
uci set stubby.global.trigger="wan"
uci set stubby.global.triggerdelay="15"
stubby_add_resolver "dns.opendns.com" "2620:119:35::35"
stubby_add_resolver "dns.opendns.com" "2620:119:53::53"
stubby_add_resolver "dns.opendns.com" "208.67.222.222"
stubby_add_resolver "dns.opendns.com" "208.67.220.220"
uci commit stubby

uci delete firewall.dns_int
uci set firewall.dns_int="redirect"
uci set firewall.dns_int.name="Intercept-DNS"
uci set firewall.dns_int.src="lan"
uci set firewall.dns_int.src_dport="53"
uci set firewall.dns_int.proto="tcp udp"
uci set firewall.dns_int.target="DNAT"
uci commit firewall

exit 0