---
- name: Set tempdir
  ansible.builtin.set_fact:
    firmware_tempdir: "{{ firmware_output | dirname }}/"

- name: Set OpenWRT download url
  ansible.builtin.set_fact:
    # https://downloads.openwrt.org/snapshots/targets/x86/64/
    # https://downloads.openwrt.org/releases/22.03.4/targets/x86/64/
    firmware_download_url: >-
      https://downloads.openwrt.org/{{
      'releases/' + firmware_version if firmware_version else 'snapshots'
      }}/targets/{{ firmware_target }}/{{
      firmware_subtarget }}/

- name: Set firmware download url
  ansible.builtin.set_fact:
    # https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz
    # https://downloads.openwrt.org/releases/22.03.4/targets/x86/64/openwrt-22.03.4-x86-64-generic-ext4-combined-efi.img.gz
    firmware_image_url: >-
      {{ firmware_download_url }}openwrt{{
      '-' + firmware_version if firmware_version }}-{{
      firmware_target }}-{{
      firmware_subtarget }}-{{
      firmware_profile }}-{{
      firmware_image }}.img.gz

- name: Set firmware image archive
  ansible.builtin.set_fact:
    # openwrt-22.03.4-x86-64-generic-ext4-combined-efi.img.gz
    firmware_image_archive: "{{ firmware_image_url | basename }}"

- name: Download sha256sums file
  ansible.builtin.get_url:
    url: "{{ firmware_download_url }}sha256sums"
    dest: "{{ firmware_tempdir }}sha256sums"
    mode: u=rw,g=r,o=r
  delegate_to: localhost
  become: false

- name: Set imagebuilder archive sha256
  ansible.builtin.set_fact:
    firmware_image_checksum: >-
      {{ 'sha256:' +
        (
          lookup('file', firmware_tempdir + '/sha256sums') |
          regex_search('([a-zA-Z0-9]+) \*' + firmware_image_archive.replace('.', '\.'), '\1') |
          first
        )
      }}

- name: Download firmware
  ansible.builtin.get_url:
    url: "{{ firmware_image_url }}"
    dest: "{{ firmware_output }}"
    checksum: "{{ firmware_image_checksum }}"
    mode: u=rw,g=r,o=r
  delegate_to: localhost
  become: false
