---
- name: Install DDNS packages
  community.general.opkg:
    name: "{{ packages | join(',') }}"
    state: present
  vars:
    packages:
      - curl
      - drill
      - luci-app-ddns

- name: Cleanup default myddns_ipv4 config
  uci:
    command: absent
    key: ddns.myddns_ipv4

- name: Cleanup default myddns_ipv6 config
  uci:
    command: absent
    key: ddns.myddns_ipv6

- name: Adding configuration {{ ddns_uci_service }}
  uci:
    command: section
    config: ddns
    name: "{{ ddns_uci_service }}"
    type: service
    value:
      interface: wan
      ip_source: network
      ip_network: wan
      enabled: 1
      use_ipv6: 0
      service_name: "{{ ddns_service_name }}"
      lookup_host: "{{ ddns_lookup_host }}"
      domain: "{{ ddns_domain }}"
      username: "{{ ddns_username }}"
      password: "{{ ddns_password }}"
      use_https: 1
      cacert: /etc/ssl/certs
    replace: true

- name: Commit
  uci:
    command: commit
    key: ddns

- name: Reload config
  ansible.builtin.command: reload_config
  changed_when: false
