---
- name: Commit
  uci:
    command: commit
  listen: Apply

- name: Reboot
  nohup:
    command: reboot
  listen: Apply

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 300
    delay: 20
  listen: Apply
