---
- name: Trigger reboot (non-blocking)
  ansible.builtin.command: "reboot &"
  async: 1
  poll: 0
  changed_when: true
  failed_when: false

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 60
    delay: 10

- name: Wait for internet access
  ansible.builtin.include_role:
    name: wait_internet

- name: Update opkg cache
  community.general.opkg:
    name: opkg
    update_cache: true
  register: reboot_opkg_update
  failed_when: reboot_opkg_update.failed
  changed_when: not reboot_opkg_update.failed
