---
- name: Trigger reboot
  nohup:
    command: reboot

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 60
    delay: 10

- name: Wait for internet access
  ansible.builtin.include_role:
    name: wait_internet

- name: Update opkg cache
  community.general.opkg:
    name: opkg
    update_cache: true
  register: _opkg_update
  failed_when: _opkg_update.failed
  changed_when: not _opkg_update.failed
