---
- name: Setup firewall, adding DNS redirection
  notify: Apply
  uci:
    command: section
    config: firewall
    name: dns_intercept
    type: redirect
    value:
      name: Intercept-DNS
      src: lan
      src_dport: 53
      proto: tcp udp
      target: DNAT
    replace: true
