---
- name: Create Unifi controller container
  community.docker.docker_container:
    name: unifi-controller
    image: lscr.io/linuxserver/unifi-controller:7.3.83
    state: started
    detach: true
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Paris
    volumes:
      - "{{ docker_unifi_config_volume_name }}:/config"
    networks:
      - name: lan20
        ipv4_address: "{{ docker_unifi_ip }}"

- name: Get infos on volume "{{ docker_unifi_config_volume_name }}"
  community.docker.docker_volume_info:
    name: "{{ docker_unifi_config_volume_name }}"
  register: docker_unifi_volume_info_result

- name: Print unifi system.properties file path
  ansible.builtin.debug:
    msg: "{{ docker_unifi_volume_info_result.volume.Mountpoint + '/data/system.properties' }}"

- name: Change controller UI https port to 443
  ansible.builtin.lineinfile:
    path: "{{ docker_unifi_volume_info_result.volume.Mountpoint + '/data/system.properties' }}"
    line: unifi.https.port=443

- name: Create Unifi controller container
  community.docker.docker_container:
    name: unifi-controller
    state: started
    restart: true

- name: Create Unifi DNS entry
  uci:
    command: section
    config: dhcp
    type: domain
    find-by:
      name: unifi
    value:
      ip: "{{ docker_unifi_ip }}"

- name: Commit dhcp
  uci:
    command: commit
    key: dhcp

- name: Reload config
  ansible.builtin.command: reload_config
  changed_when: false
