---
- name: Debug local file path
  ansible.builtin.debug:
    var: install_firmware_local_file

- name: Copy image to router
  ansible.builtin.copy:
    src: "{{ install_firmware_local_file }}"
    dest: /tmp/openwrt.img.gz
    mode: u=rw,g=r,o=r

- name: Start sysupgrade process (non-blocking)
  ansible.builtin.command: "sysupgrade -n /tmp/openwrt.img.gz &"
  async: 1
  poll: 0
  changed_when: true
  failed_when: false

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 60
    delay: 10
