---
- name: Copy image to router
  ansible.builtin.copy:
    src: "{{ firmware_local_file }}"
    dest: /tmp/openwrt.img.gz
    mode: u=rw,g=r,o=r

- name: Start sysupgrade process
  nohup:
    command: sysupgrade -n /tmp/openwrt.img.gz

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 60
    delay: 10
