#!/bin/sh
# shellcheck disable=SC3010

[[ "$ACTION" = "ifup" && "$INTERFACE" = wan* ]] && {
    logger -t hotplug-iface-ntpdate "$INTERFACE up, running ntpdate to synchronize hardware clock..."
    NTP_SERVERS=$(uci -q get system.ntp.server)
    for s in $NTP_SERVERS ; do
        /usr/sbin/ntpdate -s -b -u -t 2 "$s" && break
    done
}
