---
- name: Check presence of network device br-lan.{{ vlan_id }}
  ansible.builtin.shell: |
    . /lib/functions.sh
    config_load network
    found=0
    _check_dev() {
      local section="$1"
      local name
      config_get name "$section" name
      [ "$name" = "br-lan.{{ vlan_id }}" ] && found=1
    }
    config_foreach _check_dev device
    printf '%s' "$found"
  register: network_device_check
  changed_when: false

- name: Set fact device_br_lan_exists
  ansible.builtin.set_fact:
    device_br_lan_exists: "{{ (network_device_check.stdout | default('0')) | trim == '1' }}"

- name: Create network device br-lan.{{ vlan_id }}
  ansible.builtin.shell: |
    uci add network device
    uci set network.@device[-1].name='br-lan.{{ vlan_id }}'
    uci set network.@device[-1].type='macvlan'
    uci set network.@device[-1].ifname='br-lan'
    uci set network.@device[-1].mode='bridge'
    uci commit network
  when: not device_br_lan_exists
  changed_when: true
  notify: Reload network

- name: Check presence of network interface docker{{ vlan_id }}
  ansible.builtin.command: uci show network.docker{{ vlan_id }}
  register: network_interface_check
  changed_when: false
  failed_when: false

- name: Set fact interface_docker_exists
  ansible.builtin.set_fact:
    interface_docker_exists: "{{ network_interface_check.rc == 0 }}"

- name: Create network interface docker{{ vlan_id }}
  ansible.builtin.shell: |
    uci set network.docker{{ vlan_id }}='interface'
    uci set network.docker{{ vlan_id }}.device='br-lan.{{ vlan_id }}'
    uci set network.docker{{ vlan_id }}.proto='static'
    uci set network.docker{{ vlan_id }}.ipaddr='192.168.{{ vlan_id }}.1'
    uci set network.docker{{ vlan_id }}.netmask='255.255.255.0'
    uci commit network
  when: not interface_docker_exists
  changed_when: true
  notify: Reload network

- name: Check if firewall zone docker exists
  ansible.builtin.shell: |
    set -o pipefail
    uci show firewall.docker.network | grep docker{{ vlan_id }}
  register: firewall_network_check
  changed_when: false
  failed_when: false

- name: Set fact firewall_docker_network_exists
  ansible.builtin.set_fact:
    firewall_docker_network_exists: "{{ firewall_network_check.rc == 0 }}"

- name: "Add interface to firewall docker zone: docker{{ vlan_id }}"
  ansible.builtin.shell: |
    uci add_list firewall.@zone[-1].network='docker{{ vlan_id }}'
    uci commit firewall
  when: not firewall_docker_network_exists
  changed_when: true
  notify: Reload firewall

- name: Apply pending handlers before creating the docker network
  ansible.builtin.meta: flush_handlers

- name: Create docker network macvlan{{ vlan_id }}
  community.docker.docker_network:
    name: macvlan{{ vlan_id }}
    state: present
    driver: macvlan
    driver_options:
      parent: br-lan.{{ vlan_id }}
    ipam_config:
      - subnet: 192.168.{{ vlan_id }}.0/24
        gateway: 192.168.{{ vlan_id }}.1
        iprange: 192.168.{{ vlan_id }}.253/32
