---
- name: Download and prepare the image builder
  ansible.builtin.include_tasks: 01_imagebuilder.yml

- name: Configure and build the firmware image
  ansible.builtin.include_tasks: 02_build_firmware.yml
