---
# https://hub.docker.com/_/registry
# docker run -d -p 5000:5000 --restart always --name registry registry:2
- name: Create Docker registry container
  community.docker.docker_container:
    name: registry
    image: registry:2.8.2
    state: started
    detach: true
    restart_policy: always
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Paris
    volumes:
      - "{{ docker_unifi_config_volume_name }}:/config"
    networks:
      - name: lan20
        ipv4_address: "{{ docker_unifi_ip }}"