#!/bin/sh
[ "$(uci get network.wan.vendorid)" = "neufbox_NB6VAC-directAccess" ] && exit 0

# Enable DHCP client to wan
uci set network.wan.vendorid="neufbox_NB6VAC-directAccess"
uci commit network

# resize rootfs partition
# BOOT="$(sed -n -e "\|\s/boot\s.*$|{s///p;q}" /etc/mtab)"
# PART="${BOOT##*[^0-9]}"
# DISK="${BOOT%${PART}}"
# ROOT="${DISK}$((PART+1))"
# UUID="$(lsblk -n -o PARTUUID ${ROOT})"
# LOOP="$(losetup -f)"

# echo fix | parted -l ---pretend-input-tty
# parted -s ${DISK%p} resizepart $((PART+1)) 100%
# sed -i -r -e "s|(PARTUUID=)\S+|\1${UUID}|g" /boot/grub/grub.cfg
# losetup ${LOOP} ${ROOT}
# resize2fs -f ${LOOP}
# opkg remove --autoremove lsblk losetup resize2fs parted

exit 0
